// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReHUD.Models.LapData;

#nullable disable

namespace ReHUD.Migrations
{
    [DbContext(typeof(LapDataContext))]
    [Migration("20260406140000_AddVirtualEnergyUsages")]
    partial class AddVirtualEnergyUsages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            // This migration only adds the VirtualEnergyUsages table.
            // Full model is in LapDataContextModelSnapshot.cs.
#pragma warning restore 612, 618
        }
    }
}
